#include "key_map.h"
#include <cstdint>

// clang-format off
// These values are from the HID Usage Tables.
// https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf
// The values are from the "Keyboard/Keypad" usage page (0x07), unless otherwise specified.
BiMap<uint16_t, KeyCode> int_to_keycode = {
    // --- Letters ---
    {0x04, KeyCode::A},
    {0x05, KeyCode::B},
    {0x06, KeyCode::C},
    {0x07, KeyCode::D},
    {0x08, KeyCode::E},
    {0x09, KeyCode::F},
    {0x0a, KeyCode::G},
    {0x0b, KeyCode::H},
    {0x0c, KeyCode::I},
    {0x0d, KeyCode::J},
    {0x0e, KeyCode::K},
    {0x0f, KeyCode::L},
    {0x10, KeyCode::M},
    {0x11, KeyCode::N},
    {0x12, KeyCode::O},
    {0x13, KeyCode::P},
    {0x14, KeyCode::Q},
    {0x15, KeyCode::R},
    {0x16, KeyCode::S},
    {0x17, KeyCode::T},
    {0x18, KeyCode::U},
    {0x19, KeyCode::V},
    {0x1a, KeyCode::W},
    {0x1b, KeyCode::X},
    {0x1c, KeyCode::Y},
    {0x1d, KeyCode::Z},

    // --- Number Row ---
    {0x1e, KeyCode::K1},
    {0x1f, KeyCode::K2},
    {0x20, KeyCode::K3},
    {0x21, KeyCode::K4},
    {0x22, KeyCode::K5},
    {0x23, KeyCode::K6},
    {0x24, KeyCode::K7},
    {0x25, KeyCode::K8},
    {0x26, KeyCode::K9},
    {0x27, KeyCode::K0},

    // --- Function Keys ---
    {0x3a, KeyCode::F1},
    {0x3b, KeyCode::F2},
    {0x3c, KeyCode::F3},
    {0x3d, KeyCode::F4},
    {0x3e, KeyCode::F5},
    {0x3f, KeyCode::F6},
    {0x40, KeyCode::F7},
    {0x41, KeyCode::F8},
    {0x42, KeyCode::F9},
    {0x43, KeyCode::F10},
    {0x44, KeyCode::F11},
    {0x45, KeyCode::F12},
    {0x68, KeyCode::F13},
    {0x69, KeyCode::F14},
    {0x6a, KeyCode::F15},
    {0x6b, KeyCode::F16},
    {0x6c, KeyCode::F17},
    {0x6d, KeyCode::F18},
    {0x6e, KeyCode::F19},
    {0x6f, KeyCode::F20},
    {0x70, KeyCode::F21},
    {0x71, KeyCode::F22},
    {0x72, KeyCode::F23},
    {0x73, KeyCode::F24},

    // --- Modifiers ---
    {0xe1, KeyCode::LeftShift},
    {0xe5, KeyCode::RightShift},
    {0xe0, KeyCode::LeftControl},
    {0xe4, KeyCode::RightControl},
    {0xe2, KeyCode::LeftAlt},
    {0xe6, KeyCode::RightAlt},
    {0xe3, KeyCode::LeftSuper},
    {0xe7, KeyCode::RightSuper},
    {0x39, KeyCode::CapsLock},
    {0x53, KeyCode::NumLock},
    {0x47, KeyCode::ScrollLock},

    // --- Navigation / Editing ---
    {0x29, KeyCode::Escape},
    {0x2b, KeyCode::Tab},
    {0x28, KeyCode::Enter},
    {0x2a, KeyCode::Backspace},
    {0x2c, KeyCode::Space},
    {0x49, KeyCode::Insert},
    {0x4c, KeyCode::Delete},
    {0x4a, KeyCode::Home},
    {0x4d, KeyCode::End},
    {0x4b, KeyCode::PageUp},
    {0x4e, KeyCode::PageDown},
    {0x46, KeyCode::PrintScreen},
    {0x48, KeyCode::Pause},
    {0x65, KeyCode::Menu},

    // --- Arrows ---
    {0x52, KeyCode::ArrowUp},
    {0x51, KeyCode::ArrowDown},
    {0x50, KeyCode::ArrowLeft},
    {0x4f, KeyCode::ArrowRight},

    // --- Symbols / Punctuation ---
    {0x2d, KeyCode::Minus},
    {0x2e, KeyCode::Equals},
    {0x2f, KeyCode::LeftBracket},
    {0x30, KeyCode::RightBracket},
    {0x31, KeyCode::BackSlash},
    {0x33, KeyCode::Semicolon},
    {0x34, KeyCode::Apostrophe},
    {0x35, KeyCode::Grave},
    {0x36, KeyCode::Comma},
    {0x37, KeyCode::Period},
    {0x38, KeyCode::ForwardSlash},

    // --- Numpad Keys ---
    {0x62, KeyCode::Numpad0},
    {0x59, KeyCode::Numpad1},
    {0x5a, KeyCode::Numpad2},
    {0x5b, KeyCode::Numpad3},
    {0x5c, KeyCode::Numpad4},
    {0x5d, KeyCode::Numpad5},
    {0x5e, KeyCode::Numpad6},
    {0x5f, KeyCode::Numpad7},
    {0x60, KeyCode::Numpad8},
    {0x61, KeyCode::Numpad9},
    {0x57, KeyCode::NumpadAdd},
    {0x56, KeyCode::NumpadSubtract},
    {0x55, KeyCode::NumpadMultiply},
    {0x54, KeyCode::NumpadDivide},
    {0x58, KeyCode::NumpadEnter},
    {0x63, KeyCode::NumpadDecimal},

    // --- Media Keys (from Keyboard/Keypad usage page) ---
    {0x80, KeyCode::VolumeUp},
    {0x81, KeyCode::VolumeDown},
    {0x7f, KeyCode::Mute},

    // TODO: The following keys are on the Consumer usage page (0x0C) and will not be recognized
    // by the current daemon implementation, which only listens to the Keyboard/Keypad page (0x07).
    // {0xcd, KeyCode::MediaPlayPause},
    // {0xb5, KeyCode::MediaNext},
    // {0xb6, KeyCode::MediaPrev},
    // {0xb7, KeyCode::MediaStop},
    // {0x0224, KeyCode::BrowserBack},
    // {0x0225, KeyCode::BrowserForward},
    // {0x0227, KeyCode::BrowserRefresh},
    // {0x0223, KeyCode::BrowserHome},
    // {0x018a, KeyCode::Mail},
    // {0x0192, KeyCode::Calculator},
    // {0x0194, KeyCode::Computer},
};
