#include "key_code.h"
#include "bi_map.h"
#include <QString>

BiMap<QString, KeyCode> str_to_keycode = {
    // --- Letters ---
    {"A", KeyCode::A},
    {"B", KeyCode::B},
    {"C", KeyCode::C},
    {"D", KeyCode::D},
    {"E", KeyCode::E},
    {"F", KeyCode::F},
    {"G", KeyCode::G},
    {"H", KeyCode::H},
    {"I", KeyCode::I},
    {"J", KeyCode::J},
    {"K", KeyCode::K},
    {"L", KeyCode::L},
    {"M", KeyCode::M},
    {"N", KeyCode::N},
    {"O", KeyCode::O},
    {"P", KeyCode::P},
    {"Q", KeyCode::Q},
    {"R", KeyCode::R},
    {"S", KeyCode::S},
    {"T", KeyCode::T},
    {"U", KeyCode::U},
    {"V", KeyCode::V},
    {"W", KeyCode::W},
    {"X", KeyCode::X},
    {"Y", KeyCode::Y},
    {"Z", KeyCode::Z},

    // --- Numbers ---
    {"0", KeyCode::K0},
    {"1", KeyCode::K1},
    {"2", KeyCode::K2},
    {"3", KeyCode::K3},
    {"4", KeyCode::K4},
    {"5", KeyCode::K5},
    {"6", KeyCode::K6},
    {"7", KeyCode::K7},
    {"8", KeyCode::K8},
    {"9", KeyCode::K9},

    // --- Function Keys ---
    {"F1", KeyCode::F1},
    {"F2", KeyCode::F2},
    {"F3", KeyCode::F3},
    {"F4", KeyCode::F4},
    {"F5", KeyCode::F5},
    {"F6", KeyCode::F6},
    {"F7", KeyCode::F7},
    {"F8", KeyCode::F8},
    {"F9", KeyCode::F9},
    {"F10", KeyCode::F10},
    {"F11", KeyCode::F11},
    {"F12", KeyCode::F12},
    {"F13", KeyCode::F13},
    {"F14", KeyCode::F14},
    {"F15", KeyCode::F15},
    {"F16", KeyCode::F16},
    {"F17", KeyCode::F17},
    {"F18", KeyCode::F18},
    {"F19", KeyCode::F19},
    {"F20", KeyCode::F20},
    {"F21", KeyCode::F21},
    {"F22", KeyCode::F22},
    {"F23", KeyCode::F23},
    {"F24", KeyCode::F24},

    // --- Modifiers ---
    {"LeftShift", KeyCode::LeftShift},
    {"RightShift", KeyCode::RightShift},
    {"LeftControl", KeyCode::LeftControl},
    {"RightControl", KeyCode::RightControl},
    {"LeftAlt", KeyCode::LeftAlt},
    {"RightAlt", KeyCode::RightAlt},
    {"LeftSuper", KeyCode::LeftSuper}, // Windows key, Linux super key, Command key
    {"RightSuper", KeyCode::RightSuper},

    // --- Navigation / Control ---
    {"Escape", KeyCode::Escape},
    {"Tab", KeyCode::Tab},
    {"Enter", KeyCode::Enter},
    {"Backspace", KeyCode::Backspace},
    {"Space", KeyCode::Space},
    {"Insert", KeyCode::Insert},
    {"Delete", KeyCode::Delete},
    {"Home", KeyCode::Home},
    {"End", KeyCode::End},
    {"PageUp", KeyCode::PageUp},
    {"PageDown", KeyCode::PageDown},
    {"PrintScreen", KeyCode::PrintScreen},
    {"Pause", KeyCode::Pause},
    {"Menu", KeyCode::Menu},
    {"CapsLock", KeyCode::CapsLock},
    {"NumLock", KeyCode::NumLock},
    {"ScrollLock", KeyCode::ScrollLock},

    // --- Arrows ---
    {"ArrowUp", KeyCode::ArrowUp},
    {"ArrowDown", KeyCode::ArrowDown},
    {"ArrowLeft", KeyCode::ArrowLeft},
    {"ArrowRight", KeyCode::ArrowRight},

    // --- Symbols / Punctuation ---
    {"Minus", KeyCode::Minus},
    {"Equals", KeyCode::Equals},
    {"LeftBracket", KeyCode::LeftBracket},
    {"RightBracket", KeyCode::RightBracket},
    {"Backslash", KeyCode::BackSlash},
    {"Semicolon", KeyCode::Semicolon},
    {"Apostrophe", KeyCode::Apostrophe},
    {"Grave", KeyCode::Grave},
    {"Comma", KeyCode::Comma},
    {"Period", KeyCode::Period},
    {"Slash", KeyCode::ForwardSlash},

    // --- Numpad ---
    {"Numpad0", KeyCode::Numpad0},
    {"Numpad1", KeyCode::Numpad1},
    {"Numpad2", KeyCode::Numpad2},
    {"Numpad3", KeyCode::Numpad3},
    {"Numpad4", KeyCode::Numpad4},
    {"Numpad5", KeyCode::Numpad5},
    {"Numpad6", KeyCode::Numpad6},
    {"Numpad7", KeyCode::Numpad7},
    {"Numpad8", KeyCode::Numpad8},
    {"Numpad9", KeyCode::Numpad9},
    {"NumpadAdd", KeyCode::NumpadAdd},
    {"NumpadSubtract", KeyCode::NumpadSubtract},
    {"NumpadMultiply", KeyCode::NumpadMultiply},
    {"NumpadDivide", KeyCode::NumpadDivide},
    {"NumpadEnter", KeyCode::NumpadEnter},
    {"NumpadDecimal", KeyCode::NumpadDecimal},

    // --- Media / System ---
    {"VolumeUp", KeyCode::VolumeUp},
    {"VolumeDown", KeyCode::VolumeDown},
    {"Mute", KeyCode::Mute},
    {"MediaNext", KeyCode::MediaNext},
    {"MediaPrev", KeyCode::MediaPrev},
    {"MediaPlayPause", KeyCode::MediaPlayPause},
    {"MediaStop", KeyCode::MediaStop},
    {"BrowserBack", KeyCode::BrowserBack},
    {"BrowserForward", KeyCode::BrowserForward},
    {"BrowserRefresh", KeyCode::BrowserRefresh},
    {"BrowserStop", KeyCode::BrowserStop},
    {"BrowserHome", KeyCode::BrowserHome},
    {"Mail", KeyCode::Mail},
    {"Calculator", KeyCode::Calculator},
    {"Computer", KeyCode::Computer}};
